CREATE TABLE USUARIO(
    ID_USUARIO SMALLSERIAL,
    NICK VARCHAR(30) NOT NULL,
    PASS VARCHAR(30) NOT NULL,
    TLF_USUARIO VARCHAR(),
    NOMBRE_USUARIO VARCHAR(30) NOT NULL,
    APELLIDO_1_USUARIO VARCHAR(30) NOT NULL,
    APELLIDO_2_USUARIO VARCHAR(30) NOT NULL,
    EMAIL_USUARIO VARCHAR(150) NOT NULL
);

CREATE TABLE VALORACION(
    ID_VALORACION SMALLSERIAL,
    ID_USUARIO SMALLSERIAL,
    ESTRELLAS NUMERIC(1,0) NOT NULL,
    COMENTARIO VARCHAR(255)
);

CREATE TABLE DIRECCION_CLIENTE(
    ID_DIRECCION_CLIENTE SMALLSERIAL,
    ID_USUARIO SMALLSERIAL,
    PAIS VARCHAR(50) NOT NULL,
    PROVINCIA VARCHAR(50) NOT NULL,
    CIUDAD VARCHAR(50) NOT NULL,
    CP INTEGER(6,0) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL
);

CREATE TABLE VENTA(
    ID_VENTA SMALLSERIAL,
    ID_USUARIO SMALLSERIAL,
    ID_DIRECCION_CLIENTE SMALLSERIAL,
    DATE NOT NULL -- YYYY-MM-DD
);
CREATE TABLE PRODUCTO(
    ID_PRODUCTO SMALLSERIAL,
    NOMBRE_PRODUCTO VARCHAR(100) NOT NULL,
    DESCRIPCION_PRODUCTO VARCHAR(100) NOT NULL,
    MARCA_PRODUCTO VARCHAR() NOT NULL,
    PRECIO_PRODUCTO INTEGER NOT NULL,
    IMAGEN_PRODUCTO VARCHAR(250) NOT NULL,
    
;)

CREATE TABLE FAVORITO(

;)