ALTER TABLE PRODUCTO
DROP CONSTRAINT FK_PRODUCTO_PROVEEDOR;
ALTER TABLE CLIENTE_PRODUCTO
DROP CONSTRAINT FK_CLIENTE_PRODUCTO_idcliente;
ALTER TABLE CLIENTE_PRODUCTO
DROP CONSTRAINT FK_CLIENTE_PRODUCTO_idproducto;

DROP TABLE PROVEEDOR;
DROP TABLE CLIENTE_PRODUCTO;
DROP TABLE PRODUCTO;
DROP TABLE CLIENTE;

CREATE TABLE PRODUCTO(
    idProducto INT GENERATED ALWAYS AS IDENTITY,
    idProveedor INT,
    nombreProducto VARCHAR2(100),
    precioProducto INT
);

CREATE TABLE CLIENTE(
    idCliente INT GENERATED ALWAYS AS IDENTITY,
    nombreCliente VARCHAR2(50),
    apellidosCliente VARCHAR2(100),
    dniCliente VARCHAR2(9),
    direccionCliente VARCHAR2(200),
    fechaNacimiento DATE
);

CREATE TABLE CLIENTE_PRODUCTO(
    idClienteProducto INT GENERATED ALWAYS AS IDENTITY,
    idCliente INT,
    idProducto INT
);


CREATE TABLE PROVEEDOR(
    idProveedor INT GENERATED ALWAYS AS IDENTITY,
    NIF VARCHAR2(9),
    nombreProveedor VARCHAR2(100),
    direccionProveedor VARCHAR2(200)
);
ALTER TABLE PROVEEDOR
ADD CONSTRAINT PK_PROVEEDOR PRIMARY KEY (idProveedor);

ALTER TABLE PRODUCTO
ADD CONSTRAINT PK_PRODUCTO PRIMARY KEY (idProducto);

ALTER TABLE CLIENTE
ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (idCliente);

ALTER TABLE CLIENTE_PRODUCTO
ADD CONSTRAINT PK_CLIENTE_PRODUCTO PRIMARY KEY (idClienteProducto);


ALTER TABLE PRODUCTO
ADD CONSTRAINT FK_PRODUCTO_PROVEEDOR FOREIGN KEY (idProveedor) REFERENCES PROVEEDOR (idProveedor);
ALTER TABLE CLIENTE_PRODUCTO
ADD CONSTRAINT FK_CLIENTE_PRODUCTO_idcliente FOREIGN KEY (idCliente) REFERENCES CLIENTE (idCliente);
ALTER TABLE CLIENTE_PRODUCTO
ADD CONSTRAINT FK_CLIENTE_PRODUCTO_idproducto FOREIGN KEY (idProducto) REFERENCES PRODUCTO (idProducto);
ALTER TABLE CLIENTE_PRODUCTO
ADD CONSTRAINT UK_CLIENTE_PRODUCTO UNIQUE(idCliente, idProducto);

