-- Cambiar el formato de fecha
SET datestyle = 'ISO, YMD';

-- Eliminar restricciones de clave foránea
ALTER TABLE Vender_proveedor DROP CONSTRAINT FK_Vender_proveedor_PROVEEDOR;
ALTER TABLE Vender_proveedor DROP CONSTRAINT FK_Vender_proveedor_PRODUCTO;
ALTER TABLE HOJA_PEDIDO DROP CONSTRAINT FK_HOJA_PEDIDO_VENDER_PROVEEDOR;
ALTER TABLE ALBARAN DROP CONSTRAINT FK_ALBARAN_VENDER_PROVEEDOR;
ALTER TABLE Vender_particular DROP CONSTRAINT FK_Vender_particular_PARTICULAR;
ALTER TABLE Vender_particular DROP CONSTRAINT FK_Vender_particular_PRODUCTO;
ALTER TABLE DETALLE_NOTA_PAGO DROP CONSTRAINT FK_DETALLE_NOTA_PAGO_NOTA_PAGO;
ALTER TABLE DETALLE_NOTA_PAGO DROP CONSTRAINT FK_DETALLE_NOTA_PAGO_PRODUCTO;
ALTER TABLE NOTA_PAGO DROP CONSTRAINT FK_NOTA_PAGO_PARTICULAR;
ALTER TABLE DETALLE_HOJA_PEDIDO DROP CONSTRAINT FK_DETALLE_HOJA_PEDIDO_HOJA_PEDIDO;
ALTER TABLE DETALLE_HOJA_PEDIDO DROP CONSTRAINT FK_DETALLE_HOJA_PEDIDO_PRODUCTO;
ALTER TABLE DETALLE_ALBARAN DROP CONSTRAINT FK_DETALLE_ALBARAN_ALBARAN;
ALTER TABLE DETALLE_ALBARAN DROP CONSTRAINT FK_DETALLE_ALBARAN_PRODUCTO;

-- Eliminar tablas
DROP TABLE Vender_particular;
DROP TABLE DETALLE_NOTA_PAGO;
DROP TABLE Vender_proveedor;
DROP TABLE DETALLE_HOJA_PEDIDO;
DROP TABLE DETALLE_ALBARAN;
DROP TABLE NOTA_PAGO;
DROP TABLE PARTICULAR;
DROP TABLE PRODUCTO;
DROP TABLE PROVEEDOR;
DROP TABLE HOJA_PEDIDO;
DROP TABLE ALBARAN;
DROP TABLE CLIENTE;

-- Crear tablas
CREATE TABLE PARTICULAR (
    ID_PARTICULAR SERIAL,
    DNI_PARTICULAR VARCHAR(10) NOT NULL,
    NOMBRE_PARTICULAR VARCHAR(100) NOT NULL,
    TLF_PARTICULAR VARCHAR(15),
    DIRECCION_PARTICULAR VARCHAR(200)
);

CREATE TABLE NOTA_PAGO (
    ID_NOTA_PAGO SERIAL,
    ID_PARTICULAR INT,
    FECHA DATE NOT NULL,
    FIRMA VARCHAR(200) NOT NULL
);

CREATE TABLE PRODUCTO (
    ID_PRODUCTO SERIAL,
    NOMBRE_PRODUCTO VARCHAR(100) NOT NULL,
    DESCRIPCION_PRODUCTO VARCHAR(200),
    PRECIO_UNIDAD NUMERIC(10, 2) NOT NULL
);

CREATE TABLE PROVEEDOR (
    ID_PROVEEDOR SERIAL,
    NOMBRE_PROVEEDOR VARCHAR(100) NOT NULL,
    DIRECCION_PROVEEDOR VARCHAR(200),
    TLF_PROVEEDOR VARCHAR(15),
    URL_PROVEEDOR VARCHAR(200)
);

CREATE TABLE HOJA_PEDIDO (
    ID_HOJA_PEDIDO SERIAL,
    ID_VENDER_PROVEEDOR INT,
    FECHA_PEDIDO DATE NOT NULL,
    HORA_PEDIDO VARCHAR(5),
    DIRECCION_ENVIO VARCHAR(200)
);

CREATE TABLE ALBARAN (
    ID_ALBARAN SERIAL,
    ID_VENDER_PROVEEDOR INT,
    FECHA_ALBARAN DATE NOT NULL,
    HORA_ALBARAN VARCHAR(5)
);

CREATE TABLE Vender_particular (
    ID_VENDER_PARTICULAR SERIAL,
    ID_PARTICULAR INT,
    ID_PRODUCTO INT
);

CREATE TABLE DETALLE_NOTA_PAGO (
    ID_DETALLE_NOTA_PAGO SERIAL,
    ID_NOTA_PAGO INT,
    ID_PRODUCTO INT,
    CANTIDAD_NOTA_PAGO INT
);

CREATE TABLE Vender_proveedor (
    ID_VENDER_PROVEEDOR SERIAL,
    ID_PROVEEDOR INT,
    ID_PRODUCTO INT
);

CREATE TABLE DETALLE_HOJA_PEDIDO (
    ID_DETALLE_HOJA_PEDIDO SERIAL,
    ID_HOJA_PEDIDO INT,
    ID_PRODUCTO INT,
    CANTIDAD_PEDIDO INT
);

CREATE TABLE DETALLE_ALBARAN (
    ID_DETALLE_ALBARAN SERIAL,
    ID_ALBARAN INT,
    ID_PRODUCTO INT,
    CANTIDAD_ALBARAN INT
);

CREATE TABLE CLIENTE (
    ID_CLIENTE SERIAL,
    USUARIO VARCHAR(30),
    PASS VARCHAR(30),
    TLF VARCHAR(9),
    NOMBRE VARCHAR(30),
    APELLIDO_1 VARCHAR(50),
    APELLIDO_2 VARCHAR(50),
    EMAIL VARCHAR(200)
);

-- Agregar restricciones de clave primaria y clave foránea
ALTER TABLE PARTICULAR ADD CONSTRAINT PK_PARTICULAR PRIMARY KEY (ID_PARTICULAR);

ALTER TABLE NOTA_PAGO ADD CONSTRAINT PK_NOTA_PAGO PRIMARY KEY (ID_NOTA_PAGO);
ALTER TABLE NOTA_PAGO ADD CONSTRAINT FK_NOTA_PAGO_PARTICULAR FOREIGN KEY (ID_PARTICULAR) REFERENCES PARTICULAR (ID_PARTICULAR);

ALTER TABLE PRODUCTO ADD CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO);

ALTER TABLE DETALLE_NOTA_PAGO ADD CONSTRAINT PK_DETALLE_NOTA_PAGO PRIMARY KEY (ID_DETALLE_NOTA_PAGO);
ALTER TABLE DETALLE_NOTA_PAGO ADD CONSTRAINT UK_DETALLE_NOTA_PAGO UNIQUE (ID_DETALLE_NOTA_PAGO, ID_PRODUCTO, ID_NOTA_PAGO);
ALTER TABLE DETALLE_NOTA_PAGO ADD CONSTRAINT FK_DETALLE_NOTA_PAGO_NOTA_PAGO FOREIGN KEY (ID_NOTA_PAGO) REFERENCES NOTA_PAGO (ID_NOTA_PAGO);
ALTER TABLE DETALLE_NOTA_PAGO ADD CONSTRAINT FK_DETALLE_NOTA_PAGO_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO);

ALTER TABLE Vender_particular ADD CONSTRAINT PK_Vender_particular PRIMARY KEY (ID_VENDER_PARTICULAR);
ALTER TABLE Vender_particular ADD CONSTRAINT UK_Vender_particular UNIQUE (ID_VENDER_PARTICULAR, ID_PRODUCTO, ID_PARTICULAR);
ALTER TABLE Vender_particular ADD CONSTRAINT FK_Vender_particular_PARTICULAR FOREIGN KEY (ID_PARTICULAR) REFERENCES PARTICULAR (ID_PARTICULAR);
ALTER TABLE Vender_particular ADD CONSTRAINT FK_Vender_particular_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO);

ALTER TABLE PROVEEDOR ADD CONSTRAINT PK_PROVEEDOR PRIMARY KEY (ID_PROVEEDOR);

ALTER TABLE Vender_proveedor ADD CONSTRAINT PK_Vender_proveedor PRIMARY KEY (ID_VENDER_PROVEEDOR);
ALTER TABLE Vender_proveedor ADD CONSTRAINT UK_Vender_proveedor UNIQUE (ID_VENDER_PROVEEDOR, ID_PRODUCTO, ID_PROVEEDOR);
ALTER TABLE Vender_proveedor ADD CONSTRAINT FK_Vender_proveedor_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR (ID_PROVEEDOR);
ALTER TABLE Vender_proveedor ADD CONSTRAINT FK_Vender_proveedor_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO);

ALTER TABLE HOJA_PEDIDO ADD CONSTRAINT PK_HOJA_PEDIDO PRIMARY KEY (ID_HOJA_PEDIDO);
ALTER TABLE HOJA_PEDIDO ADD CONSTRAINT FK_HOJA_PEDIDO_VENDER_PROVEEDOR FOREIGN KEY (ID_VENDER_PROVEEDOR) REFERENCES Vender_proveedor (ID_VENDER_PROVEEDOR);

ALTER TABLE ALBARAN ADD CONSTRAINT PK_ALBARAN PRIMARY KEY (ID_ALBARAN);
ALTER TABLE ALBARAN ADD CONSTRAINT FK_ALBARAN_VENDER_PROVEEDOR FOREIGN KEY (ID_VENDER_PROVEEDOR) REFERENCES Vender_proveedor (ID_VENDER_PROVEEDOR);

ALTER TABLE DETALLE_HOJA_PEDIDO ADD CONSTRAINT PK_DETALLE_HOJA_PEDIDO PRIMARY KEY (ID_DETALLE_HOJA_PEDIDO);
ALTER TABLE DETALLE_HOJA_PEDIDO ADD CONSTRAINT UK_DETALLE_HOJA_PEDIDO UNIQUE (ID_DETALLE_HOJA_PEDIDO, ID_PRODUCTO, ID_HOJA_PEDIDO);
ALTER TABLE DETALLE_HOJA_PEDIDO ADD CONSTRAINT FK_DETALLE_HOJA_PEDIDO_HOJA_PEDIDO FOREIGN KEY (ID_HOJA_PEDIDO) REFERENCES HOJA_PEDIDO (ID_HOJA_PEDIDO);
ALTER TABLE DETALLE_HOJA_PEDIDO ADD CONSTRAINT FK_DETALLE_HOJA_PEDIDO_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO);

ALTER TABLE DETALLE_ALBARAN ADD CONSTRAINT PK_DETALLE_ALBARAN PRIMARY KEY (ID_DETALLE_ALBARAN);
ALTER TABLE DETALLE_ALBARAN ADD CONSTRAINT UK_DETALLE_ALBARAN UNIQUE (ID_DETALLE_ALBARAN, ID_PRODUCTO, ID_ALBARAN);
ALTER TABLE DETALLE_ALBARAN ADD CONSTRAINT FK_DETALLE_ALBARAN_ALBARAN FOREIGN KEY (ID_ALBARAN) REFERENCES ALBARAN (ID_ALBARAN);
ALTER TABLE DETALLE_ALBARAN ADD CONSTRAINT FK_DETALLE_ALBARAN_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE);